version: '3.8'

services:
  db:
    container_name: database
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FrancePartage
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  dev: &dev
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    depends_on:
      - db
    build:
      context: .
      target: nestjs
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment: &dev_environment
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/FrancePartage?schema=public"
      NODE_ENV: development
      MIGRATE_DATABASE: 1
    restart: unless-stopped

  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    depends_on:
      - db
    build:
      context: .
      target: nestjs
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/FrancePartage?schema=public"
      NODE_ENV: production
      MIGRATE_DATABASE: 1
    restart: unless-stopped

  prisma-studio:
    <<: *dev
    container_name: prisma-studio
    ports:
      - 5555:5555
    environment:
      <<: *dev_environment
      MIGRATE_DATABASE: 0
    command: npx prisma studio